language: python
python: 3.5
sudo: false
env:
  - TOXENV="py27-dj17"
  - TOXENV="py33-dj17"
  - TOXENV="py34-dj17"
  - TOXENV="py27-dj18"
  - TOXENV="py33-dj18"
  - TOXENV="py34-dj18"
  - TOXENV="py27-dj19"
  - TOXENV="py34-dj19"
  - TOXENV="py35-dj19"
  - TOXENV="py27-dj110"
  - TOXENV="py34-dj110"
  - TOXENV="py35-dj110"
install:
 - pip install tox codecov
script:
 - tox
after_success:
 - codecov
