language: python
python: 3.5
sudo: false
env:
  - TOXENV="py27-dj17"
  - TOXENV="py33-dj17"
  - TOXENV="py34-dj17"
  - TOXENV="py27-dj18"
  - TOXENV="py33-dj18"
  - TOXENV="py34-dj18"
  - TOXENV="py27-dj19"
  - TOXENV="py34-dj19"
  - TOXENV="py35-dj19"
  - TOXENV="py27-dj110"
  - TOXENV="py34-dj110"
  - TOXENV="py35-dj110"
install:
    - pip install -q $DJANGO
    - pip install -r requirements.txt
    - pip install coveralls

script:
  - coverage run runtests.py
  
after_success:
  - coveralls

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="Django>=1.6.0,<1.7.0"
    - python: "3.5"
      env: DJANGO="Django>=1.6.0,<1.7.0"
    - python: "3.5"
      env: DJANGO="Django>=1.7.0,<1.8.0"
    - python: "3.3"
      env: DJANGO="Django>=1.9.0,<1.10.0"
