language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10

install:
    - pip install -q $DJANGO

script:
  - python runtests.py

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=1.7
    - python: "3.3"
      env: DJANGO=1.8
    - python: "3.3"
      env: DJANGO=1.9
    - python: "3.3"
      env: DJANGO=1.10
